name: Deploy Frontend to EC2-c

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  frontend-c:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. SSH 키 설정
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.QWE_PEM }}" > ~/.ssh/qwe.pem
          chmod 600 ~/.ssh/qwe.pem

      # 3. EC2에 배포
      - name: Deploy to EC2
        run: |
          echo "Step 1: Connecting to EC2 instance (15.164.217.150)"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/qwe.pem ec2-user@15.164.217.150 << EOF
            echo "Connected to EC2 (15.164.217.150)"

            # Docker 이미지 가져오기
            docker pull ckdgkim/frontendproject:front-1
          
            # 네트워크 생성 (이미 존재하면 무시)
            docker network create mynetwork || true

            # 기존 컨테이너 종료 및 삭제
            docker stop frontend-container-c || true
            docker rm frontend-container-c || true

            # 새 컨테이너 실행
            docker run -d  --name frontend-container-c \
              --network mynetwork \
              -p 80:80 \
              ckdgkim/frontendproject:front-1
          EOF
